[project]
name = "rocrate-action-recorder"
description = "Record calls of Python CLI commands into a Research Object Crate"
readme = "README.md"
authors = [{ name = "Stefan Verhoeven", email = "stefan.verhoeven@gmail.com" }]
requires-python = ">=3.13"
dependencies = ["rocrate==0.15.0"]
dynamic = ["version"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries",
]
[project.urls]
"Homepage" = "https://github.com/i-VRESSE/rocrate-action-recorder"
"Repository" = "https://github.com/i-VRESSE/rocrate-action-recorder"
"Issues" = "https://github.com/i-VRESSE/rocrate-action-recorder/issues"
"Documentation" = "https://rocrate-action-recorder.readthedocs.io/"

[project.optional-dependencies]
click = ["click>=8.1.0"]
cyclopts = ["cyclopts>=4.10.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/rocrate_action_recorder/__about__.py"

[dependency-groups]
dev = [{ include-group = "typecheck" }, { include-group = "test" }]
typecheck = ["pyright>=1.1.411"]
test = [
  "click>=8.1.0",
  "pytest>=9.0.2",
  "pytest-asyncio>=0.21.0",
  "pytest-cov>=7.0.0",
  "roc-validator>=0.10.0",
  "cyclopts>=4.16.1",
  "pydantic>=2.0.0",
  "attrs>=24.0.0",
]
docs = [
  "sphinx>=9.1.0",
  "myst_parser>=0.13",
  "sphinx-autoapi",
  "sphinx_copybutton",
  "sphinx_autodoc_typehints",
  "furo>=2023.08.17",
]

[tool.pytest]
minversion = "9.0"
strict = true
addopts = ["--doctest-modules", "--import-mode=importlib"]
filterwarnings = ["error"]
log_level = "INFO"
testpaths = ["tests", "src"]

[tool.coverage]
run.source = ["src"]
run.branch = true

[tool.pyright]
include = ['src']
pythonVersion = "3.14"
pythonPlatform = "Linux"
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 120

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["rocrate_action_recorder"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]
